export const crypto = {
  name: 'crypto',
  rules: [
    //# > Exchange
    'DOMAIN-SUFFIX,aex.com',
    'DOMAIN-SUFFIX,bibox.com',
    'DOMAIN-SUFFIX,bitfinex.com',
    'DOMAIN-SUFFIX,bithumb.com',
    'DOMAIN-SUFFIX,bitmex.com',
    'DOMAIN-SUFFIX,bitstamp.net',
    'DOMAIN-SUFFIX,bittrex.com',
    'DOMAIN-SUFFIX,bybit.com',
    'DOMAIN-SUFFIX,coinbase.com',
    'DOMAIN-SUFFIX,coincheck.com',
    'DOMAIN-SUFFIX,gemini.com',
    'DOMAIN-SUFFIX,korbit.co.kr',
    'DOMAIN-SUFFIX,kraken.com',
    'DOMAIN-SUFFIX,kucoin.com',
    'DOMAIN-SUFFIX,liquid.com',
    'DOMAIN-SUFFIX,poloniex.com',
    'DOMAIN-SUFFIX,bitbank.cc',
    'DOMAIN-SUFFIX,bitcoin.org',
    'DOMAIN-SUFFIX,bitquick.co',
    'DOMAIN-SUFFIX,btcbox.co.jp',
    'DOMAIN-SUFFIX,cex.io',
    'DOMAIN-SUFFIX,dogecoin.com',
    'DOMAIN-SUFFIX,paxful.com',
    'DOMAIN-SUFFIX,tether.to',
    'DOMAIN-SUFFIX,dydx.exchange',
    'DOMAIN-SUFFIX,solana.com',
    'DOMAIN-SUFFIX,avax.network',
    'DOMAIN-SUFFIX,optimism.io',
    'DOMAIN-SUFFIX,arbitrum.io',
    'DOMAIN-SUFFIX,poly.network',
    'DOMAIN-SUFFIX,zkscan.io',
    'DOMAIN-SUFFIX,zksync.io',
    'DOMAIN-SUFFIX,boba.network',

    //# > Binance
    'DOMAIN-SUFFIX,binance.cc',
    'DOMAIN-SUFFIX,binance.cloud',
    'DOMAIN-SUFFIX,binance.com',
    'DOMAIN-SUFFIX,binance.im',
    'DOMAIN-SUFFIX,binance.me',
    'DOMAIN-SUFFIX,binance.us',
    'DOMAIN-SUFFIX,bnappzh.co',
    'DOMAIN-SUFFIX,bnappzh.com',
    'DOMAIN-SUFFIX,bnbstatic.com',
    'DOMAIN-SUFFIX,bntrace.com',
    'DOMAIN-SUFFIX,binance.charity',
    'DOMAIN-SUFFIX,binance.co',
    'DOMAIN-SUFFIX,binance.info',
    'DOMAIN-SUFFIX,binance.net',
    'DOMAIN-SUFFIX,binance.org',
    'DOMAIN-SUFFIX,binance.vision',
    'DOMAIN-SUFFIX,binanceapi.com',
    'DOMAIN-SUFFIX,binancezh.be',
    'DOMAIN-SUFFIX,binancezh.biz',
    'DOMAIN-SUFFIX,binancezh.cc',
    'DOMAIN-SUFFIX,binancezh.co',
    'DOMAIN-SUFFIX,binancezh.com',
    'DOMAIN-SUFFIX,binancezh.info',
    'DOMAIN-SUFFIX,binancezh.ink',
    'DOMAIN-SUFFIX,binancezh.kim',
    'DOMAIN-SUFFIX,binancezh.link',
    'DOMAIN-SUFFIX,binancezh.live',
    'DOMAIN-SUFFIX,binancezh.mobi',
    'DOMAIN-SUFFIX,binancezh.net',
    'DOMAIN-SUFFIX,binancezh.pro',
    'DOMAIN-SUFFIX,binancezh.sh',
    'DOMAIN-SUFFIX,binancezh.top',
    'DOMAIN-SUFFIX,bnappzh.mobi',
    'DOMAIN-SUFFIX,bsc.getblock.io',
    'DOMAIN-SUFFIX,bscscan.com',
    'PROCESS-NAME,Binance.exe',
    'DOMAIN-KEYWORD,binance',

    //# > Huobi
    'DOMAIN-SUFFIX,hbabit.com',
    'DOMAIN-SUFFIX,hbfile.net',
    'DOMAIN-SUFFIX,huobi.com',
    'DOMAIN-SUFFIX,huobi.me',
    'DOMAIN-SUFFIX,huobi.pro',
    'DOMAIN-SUFFIX,huobi.sc',
    'DOMAIN-SUFFIX,huobiasia.vip',
    'DOMAIN-SUFFIX,huobigroup.com',
    'DOMAIN-SUFFIX,huobitoken.com',
    'DOMAIN-SUFFIX,heco-scan.com',
    'DOMAIN-SUFFIX,hecoview.com',
    'DOMAIN-SUFFIX,huobi.br.com',
    'DOMAIN-SUFFIX,bitderiv.com',
    'DOMAIN-SUFFIX,hecochain.com',
    'DOMAIN-SUFFIX,huobi.ws',
    'DOMAIN-SUFFIX,huobi.ug',
    'DOMAIN-SUFFIX,huobi.co.ma',
    'PROCESS-NAME,Huobi.exe',
    'DOMAIN-KEYWORD,huobi',

    //# > OKX
    'DOMAIN-SUFFIX,okex.com',
    'DOMAIN-SUFFIX,okx.com',
    'DOMAIN-SUFFIX,okpool.top',
    'PROCESS-NAME,OKX.exe',
    'DOMAIN-KEYWORD,okx',

    //# > Metamask
    'DOMAIN-KEYWORD,metamask',
    'DOMAIN,token-api.metaswap.codefi.network',
    'DOMAIN,min-api.cryptocompare.com',
    'DOMAIN-SUFFIX,metamask.io',

    //# GPT/USDT
    'DOMAIN-SUFFIX,qna3.ai',

    //# 空投 IQ50
    'DOMAIN-SUFFIX,bakeryswap.org',

    'DOMAIN-SUFFIX,galxe.com',
    'DOMAIN-SUFFIX,pryzm.zone',
    'DOMAIN-SUFFIX,influpia.com',
    'DOMAIN-SUFFIX,questn.com',
    'DOMAIN-SUFFIX,brave.com',

    //# io.net
    'DOMAIN-SUFFIX,io.net',
    'DOMAIN-SUFFIX,io.solutions',

    //# trust wallet
    'DOMAIN-SUFFIX,trustwallet.com',

    //# wallet connect
    'DOMAIN-SUFFIX,walletconnect.org',
    'DOMAIN-SUFFIX,web3modal.org',
  ],
};
